# Generated by Django 3.2.6 on 2021-09-04 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
