# Generated by Django 3.2.6 on 2021-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='Light', max_length=64),
        ),
    ]
