# Generated by Django 3.2.6 on 2021-12-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211125_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='color',
        ),
    ]
