language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

env:
  # Generates a secret_key and DEBUG environment variables.
  - export SECRET_KEY=$(python manage.py shell -c 'from django.core.management import utils; print(utils.get_random_secret_key())')
  - export DEBUG=TRUE
script:
  # Run Migrations
  - python manage.py makemigrations
  - python manage.py showmigrations
  - python manage.py migrate
  - python manage.py showmigrations
  # run test with coverage
  - coverage run --source=TheLearningHub manage.py test
  # outputs coverage report
  - coverage report

