language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  # Run Migrations
  - python manage.py makemigrations
  - python manage.py migrate
  # run test with coverage
  - python manage.py collectstatic
  - coverage run --source=TheLearningHub,articles,home manage.py test
  # outputs coverage report
  - coverage report

