language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  # Run Migrations
  - python manage.py makemigrations
  - python manage.py migrate
  # run test with coverage
  - python manage.py collectstatic
  - coverage run --source=TheLearningHub,articles,home,personal_space,video_classes,products manage.py test
  # outputs coverage report
  - coverage report
  # Testing helper functions
  -  python -m unittest discover -s test/src/* -p "*_test.py" -v

