language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  # Run Migrations
  - python manage.py makemigrations
  - python manage.py showmigrations
  - python manage.py migrate
  - python manage.py showmigrations
  # run test with coverage
  - python manage.py collectstatic
  - coverage run --source=TheLearningHub manage.py test
  # outputs coverage report
  - coverage report

