# Generated by Django 3.2.6 on 2021-10-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmarks',
            old_name='name',
            new_name='content_title',
        ),
        migrations.RemoveField(
            model_name='userbookmarks',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='userbookmarks',
            name='note',
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='content_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
