# Generated by Django 3.2.6 on 2021-10-16 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_space', '0002_auto_20211011_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookmarks',
            new_name='UserBookmark',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
