# Generated by Django 3.2.6 on 2021-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0006_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='note_title',
            field=models.CharField(default='content', max_length=96),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernote',
            name='note_content',
            field=models.CharField(default='note', max_length=800),
            preserve_default=False,
        ),
    ]
