# Generated by Django 3.2.6 on 2021-10-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0008_auto_20211017_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='content_title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
    ]
