# Generated by Django 3.2.6 on 2021-10-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_classes', '0001_initial'),
        ('personal_space', '0010_auto_20211022_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernote',
            name='content_path',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='content_title',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='title',
        ),
        migrations.AddField(
            model_name='usernote',
            name='video_class_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_classes.videoclass'),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='body',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
