# Generated by Django 3.2.6 on 2021-10-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0011_auto_20211029_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernote',
            old_name='video_class_id',
            new_name='video_class',
        ),
    ]
