# Generated by Django 3.2.6 on 2021-10-29 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_classes', '0001_initial'),
        ('personal_space', '0012_rename_video_class_id_usernote_video_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNote',
            new_name='UserNoteFromVideoClass',
        ),
    ]
