# Generated by Django 3.2.6 on 2021-10-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0013_rename_usernote_usernotefromvideoclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotefromvideoclass',
            old_name='body',
            new_name='content',
        ),
    ]
