# Generated by Django 3.2.6 on 2021-11-01 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_alter_topic_options'),
        ('personal_space', '0015_userbookmark_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookmark',
            new_name='UserBookmarkArticle',
        ),
    ]
