# Generated by Django 3.2.6 on 2021-11-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0016_rename_userbookmark_userbookmarkarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmarkarticle',
            name='content_path',
        ),
        migrations.RemoveField(
            model_name='userbookmarkarticle',
            name='content_title',
        ),
        migrations.RemoveField(
            model_name='userbookmarkarticle',
            name='type',
        ),
    ]
