# Generated by Django 3.2.6 on 2021-11-25 09:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0018_alter_usernotefromvideoclass_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotefromvideoclass',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
