# Generated by Django 3.2.6 on 2021-12-22 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_classes', '0007_delete_learningfilestorage'),
        ('personal_space', '0019_alter_usernotefromvideoclass_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmarkVideoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_classes.videoclass')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
