# Generated by Django 3.2.6 on 2021-12-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_space', '0020_userbookmarkvideoclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmarkvideoclass',
            old_name='article',
            new_name='video_class',
        ),
    ]
