# Generated by Django 3.2.6 on 2021-11-22 13:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='<p>New Page, click on Edit Page to create content here.</p>', verbose_name='Content'),
        ),
    ]
