# Generated by Django 3.2.6 on 2021-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningFileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
    ]
