# Generated by Django 3.2.6 on 2021-12-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_learningfilestorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningfilestorage',
            old_name='type',
            new_name='page_source',
        ),
    ]
