# Generated by Django 3.2.6 on 2021-12-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_type_learningfilestorage_page_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningfilestorage',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
