# Generated by Django 3.2.6 on 2021-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclass',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videoclass',
            name='video_path',
            field=models.FileField(null=True, upload_to='media/videos/'),
        ),
    ]
