# Generated by Django 3.2.6 on 2021-11-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_classes', '0004_auto_20211125_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningFileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default=None, max_length=32)),
            ],
        ),
    ]
