# Generated by Django 3.2.6 on 2021-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_classes', '0005_learningfilestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningfilestorage',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='learningfilestorage',
            name='type',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
