# Generated by Django 3.2.6 on 2021-11-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_classes', '0006_auto_20211130_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningFileStorage',
        ),
    ]
