# Generated by Django 3.2.6 on 2021-11-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_usersubscription_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='order',
            field=models.CharField(max_length=1796, null=True),
        ),
    ]
