# Generated by Django 3.2.6 on 2021-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
