# Generated by Django 3.2.6 on 2021-11-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_usersubscription_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='order',
        ),
    ]
