# Generated by Django 3.2.6 on 2021-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_usersubscription_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
