# Generated by Django 3.2.6 on 2021-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='order',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
