# Generated by Django 3.2.6 on 2021-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_usersubscription_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
